server:
  port: 8083

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/school_erp}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

AUTH_SERVICE_URL: http://localhost:8081
API_GATEWAY_URL: ${API_GATEWAY_URL:http://localhost:8080}
SERVICE_AUTH_TOKEN: ${SERVICE_AUTH_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjb3JlLXNlcnZpY2UiLCJyb2xlIjoiQURNSU4iLCJ0ZW5hbnRJZCI6InB1YmxpYyIsImV4cCI6MjA5MDE2OTMzM30.UDfebAD_WnBIY8DRMT7GOXE-1kqCcSo2C5nBm3sPRuY}
