server:
  port: 8083

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/school_erp}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

AUTH_SERVICE_URL: http://localhost:8081
