server:
  port: ${PORT:8080}

spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

jwt:
  secret: ${JWT_SECRET:mysupersecretkeythatisverylongandsecure}
  expiration: ${JWT_EXPIRATION:86400000}
