server:
  port: 8083

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/school_erp_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: mysupersecretkeythatisverylongandsecure
  expiration: 86400000 # 24 hours
